package policy

// ─── Shared context ───────────────────────────────────────────────────────────

// SharedContext carries data that persists across all phases of one HTTP
// request-response lifecycle. It is embedded in every phase context.
type SharedContext struct {
	// ProjectID is the project this API belongs to.
	ProjectID string

	// RequestID is a unique identifier generated by the kernel for this request.
	RequestID string

	// Metadata is a free-form map for inter-policy communication.
	// Policies use this to pass state from the request phase to the response
	// phase (e.g., PII masking stores placeholder→original mappings here).
	// The kernel initialises this as an empty non-nil map.
	Metadata map[string]interface{}

	// API fields — populated by the kernel at request time.
	APIId         string
	APIName       string
	APIVersion    string
	APIKind       string
	APIContext    string // base path, e.g. "/petstore"
	OperationPath string // path pattern, e.g. "/pets/{id}"

	// AuthContext stores authentication-related key-value pairs (e.g. user ID).
	AuthContext map[string]string
}

// ─── Phase context types ──────────────────────────────────────────────────────

// RequestHeaderContext is provided to RequestHeaderPolicy.OnRequestHeaders.
// Only request headers are available — the body has not been read yet.
type RequestHeaderContext struct {
	*SharedContext
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
}

// ResponseHeaderContext is provided to ResponseHeaderPolicy.OnResponseHeaders.
type ResponseHeaderContext struct {
	*SharedContext
	RequestHeaders  *Headers
	ResponseHeaders *Headers
	ResponseStatus  int
}

// RequestBodyContext is provided to RequestBodyPolicy.OnRequestBody.
// The full request body is guaranteed available (EndOfStream always true).
type RequestBodyContext struct {
	*SharedContext
	Headers   *Headers
	Body      *Body
	Path      string
	Method    string
	Authority string
}

// ResponseBodyContext is provided to ResponseBodyPolicy.OnResponseBody.
// Both request and response headers plus the full response body are available.
type ResponseBodyContext struct {
	*SharedContext
	RequestHeaders  *Headers
	ResponseHeaders *Headers
	ResponseBody    *Body
	ResponseStatus  int
}

// RequestStreamContext is provided to StreamingRequestBodyPolicy.OnRequestBodyChunk.
// Headers are available on every chunk invocation.
type RequestStreamContext struct {
	*SharedContext
	Headers   *Headers
	Path      string
	Method    string
	Authority string
}

// ResponseStreamContext is provided to StreamingResponseBodyPolicy.OnResponseBodyChunk.
// Both header sets are available on every chunk invocation.
type ResponseStreamContext struct {
	*SharedContext
	RequestHeaders  *Headers
	ResponseHeaders *Headers
	ResponseStatus  int
}

// ─── Body types ───────────────────────────────────────────────────────────────

// Body represents a complete HTTP body (buffered mode).
type Body struct {
	Content     []byte // payload bytes
	EndOfStream bool   // always true in buffered mode
	Present     bool   // false if no body was sent
}

// StreamBody represents one chunk of a streaming body.
type StreamBody struct {
	Content     []byte // chunk payload
	EndOfStream bool   // true on the final chunk
}

// ─── Headers (read-only for policies) ────────────────────────────────────────

// Headers provides read-only access to HTTP headers.
// Keys are normalised to lowercase. Methods return defensive copies.
type Headers struct {
	values map[string][]string
}

// NewHeaders constructs a Headers from a raw map (kernel use only).
func NewHeaders(values map[string][]string) *Headers {
	return &Headers{values: values}
}

// Get returns all values for the named header (case-insensitive).
// Returns nil if the header is absent.
func (h *Headers) Get(name string) []string {
	v := h.values[canonicalName(name)]
	if v == nil {
		return nil
	}
	cp := make([]string, len(v))
	copy(cp, v)
	return cp
}

// Has reports whether the named header is present.
func (h *Headers) Has(name string) bool {
	_, ok := h.values[canonicalName(name)]
	return ok
}

// GetAll returns a defensive copy of all headers.
func (h *Headers) GetAll() map[string][]string {
	cp := make(map[string][]string, len(h.values))
	for k, v := range h.values {
		vs := make([]string, len(v))
		copy(vs, v)
		cp[k] = vs
	}
	return cp
}

// Iterate calls fn for each header name and its values.
func (h *Headers) Iterate(fn func(name string, values []string)) {
	for k, v := range h.values {
		cp := make([]string, len(v))
		copy(cp, v)
		fn(k, cp)
	}
}

// UnsafeInternalValues returns the underlying mutable map.
// This is for kernel use only — policies must not call this.
func (h *Headers) UnsafeInternalValues() map[string][]string {
	return h.values
}

func canonicalName(name string) string {
	// Simple lowercase normalisation; matches net/http.CanonicalHeaderKey semantics.
	b := []byte(name)
	for i, c := range b {
		if 'A' <= c && c <= 'Z' {
			b[i] = c + ('a' - 'A')
		}
	}
	return string(b)
}
