// Package piimaskingregex implements regex-based PII detection and masking.
//
// # Request side (always buffered — RequestBodyPolicy)
//
// The request body is always fully buffered so JSONPath extraction and regex
// substitution can operate on the complete payload. Returns RequestBodyAction
// which can carry an ImmediateResponse if extraction fails.
//
// # Response side — multiple calling scenarios
//
// The response side is more complex because the same policy receives different
// content formats depending on whether the upstream LLM is streaming and whether
// ALL chain policies support streaming.  The kernel (execution_context.go) routes
// each scenario as follows:
//
//	┌──────────────────────────────┬────────────────────────────────┬───────────────────────────────────┐
//	│ upstream response type        │ chain capability               │ kernel call                       │
//	├──────────────────────────────┼────────────────────────────────┼───────────────────────────────────┤
//	│ Non-streaming JSON            │ any                            │ OnResponseBody  (buffered)        │
//	│ (Content-Length, no chunked)  │                                │ content = complete JSON           │
//	├──────────────────────────────┼────────────────────────────────┼───────────────────────────────────┤
//	│ Streaming SSE / chunked       │ ALL policies: streaming        │ OnResponseBodyChunk (per flush)   │
//	│ (Transfer-Encoding: chunked   │ (StreamResponseBody=true)      │ content = SSE event(s) OR         │
//	│  or Content-Type: text/event- │                                │ complete JSON if no \n\n present  │
//	│  stream)                      │                                │ until eos=true                    │
//	├──────────────────────────────┼────────────────────────────────┼───────────────────────────────────┤
//	│ Streaming SSE / chunked       │ ANY policy: buffered-only      │ OnResponseBody (buffered)         │
//	│ (same as above)               │ (StreamResponseBody=false)     │ content = ALL SSE events          │
//	│                               │                                │ concatenated (Envoy assembled)    │
//	└──────────────────────────────┴────────────────────────────────┴───────────────────────────────────┘
//
// Because a streaming response can also be forced through the buffered path (bottom
// row), and a non-streaming response may arrive in chunks (chunked transfer encoding
// without SSE), BOTH OnResponseBody and OnResponseBodyChunk must be prepared to
// handle either plain JSON or aggregated SSE content.  The restoration logic
// (restoreInChunk) uses a simple global string replace that is format-agnostic.
//
// # Masking vs redaction
//
//   - Masking (redactPII=false): PII is replaced with [TYPE_xxxx] placeholders.
//     The mapping is stored in ctx.Metadata and restored in the response.
//   - Redaction (redactPII=true): PII is permanently replaced with "*****".
//     No restoration is needed because the original value is discarded.
package piimaskingregex

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"policy-v2/policy"
)

const (
	internalErrorStatus = 500
	internalErrorCode   = 900967
	textCleanPattern    = "^\"|\"$"
	metadataKeyPII      = "piimaskingregex:pii_entities"
)

var textCleanRe = regexp.MustCompile(textCleanPattern)

// PIIMaskingRegexPolicy masks or redacts PII in request/response bodies.
type PIIMaskingRegexPolicy struct {
	piiEntities map[string]*regexp.Regexp
	jsonPath    string
	redactPII   bool
}

// NeedsMoreData implements ChunkBuffering, telling the kernel when to flush the
// accumulated raw-chunk buffer to OnResponseBodyChunk.
//
// Strategy: flush on SSE event boundary (\n\n) — NeedsMoreDataSSE.
//
// Why a single strategy works for ALL upstream response formats:
//
//   Scenario A — true SSE stream (streaming:true, Content-Type: text/event-stream):
//     Each logical event ends with "\n\n".  The kernel accumulates raw Envoy chunks
//     until at least one "\n\n" boundary is present, then calls OnResponseBodyChunk
//     with all data up to (and including) that boundary.
//     ⚠ Trade-off: if a PII placeholder such as [EMAIL_0001] is generated by the
//     LLM token-by-token and spans two consecutive SSE events, restoration may be
//     incomplete for that flush.  The placeholder will be visible in the stream
//     until eos causes a final flush that covers the full token.  This is an
//     acceptable trade-off for maintaining streaming latency.  For guaranteed
//     restoration, implement FullBodyRequired to degrade to BUFFERED mode.
//
//   Scenario B — non-SSE chunked transfer (streaming:false, Transfer-Encoding: chunked):
//     OpenAI returns a plain JSON body using HTTP chunked transfer encoding even for
//     non-streaming requests.  Plain JSON has no "\n\n", so NeedsMoreDataSSE holds
//     every chunk until eos=true.  OnResponseBodyChunk then receives the fully
//     assembled JSON body in a single call.  Placeholder restoration works correctly.
//
//   Scenario C — forced-BUFFERED synthetic chunk (mixed-chain corner case):
//     If any co-located policy forces BUFFERED mode, the kernel ignores NeedsMoreData
//     and delivers the entire body (eos=true) in one call.  No accumulation needed.
//
// The framework ALWAYS flushes unconditionally when eos=true, regardless of this
// method's return value.
func (p *PIIMaskingRegexPolicy) NeedsMoreData(accumulated []byte, eos bool) bool {
	// Flush on SSE event boundary OR hold until eos (covers plain JSON in chunks).
	return policy.NeedsMoreDataSSE(accumulated, eos)

	// ── Alternative strategies shown here for reference ─────────────────────────
	//
	// Wait for a newline delimiter (NDJSON / newline-delimited streams):
	//   return policy.NeedsMoreDataDelimiter(accumulated, eos, '\n')
	//
	// Wait for a minimum token budget before processing (e.g. 50 tokens):
	//   return policy.NeedsMoreDataTokenBudget(accumulated, eos, 50, countTokens)
	//
	// Custom keyword trigger — hold until a specific marker appears (demo only):
	//   return !bytes.Contains(accumulated, []byte("attack"))
	//
	// Compose multiple conditions (hold until ALL are false — AND logic):
	//   return policy.NeedsMoreDataTokenBudget(accumulated, eos, 7, countTokens) ||
	//       policy.NeedsMoreDataDelimiter(accumulated, eos, '.') ||
	//       !bytes.Contains(accumulated, []byte("attack"))
}

// countTokens returns a simple whitespace-based token count.
// Replace with a proper tokeniser (e.g. tiktoken) for token-accurate budgeting.
func countTokens(data []byte) int {
	return len(strings.Fields(string(data)))
}

// Compile-time interface assertions.
var (
	_ policy.RequestBodyPolicy           = (*PIIMaskingRegexPolicy)(nil)
	_ policy.StreamingResponseBodyPolicy = (*PIIMaskingRegexPolicy)(nil)
	_ policy.ChunkBuffering              = (*PIIMaskingRegexPolicy)(nil)
)

func GetPolicy(
	metadata policy.PolicyMetadata,
	params map[string]interface{},
) (policy.Policy, error) {
	p := &PIIMaskingRegexPolicy{}

	entities, err := parsePIIEntities(params)
	if err != nil {
		return nil, fmt.Errorf("invalid parameters: %w", err)
	}
	p.piiEntities = entities

	if v, ok := params["jsonPath"]; ok {
		s, ok := v.(string)
		if !ok {
			return nil, fmt.Errorf("'jsonPath' must be a string")
		}
		p.jsonPath = s
	}

	if v, ok := params["redactPII"]; ok {
		b, ok := v.(bool)
		if !ok {
			return nil, fmt.Errorf("'redactPII' must be a boolean")
		}
		p.redactPII = b
	}

	return p, nil
}

// ─── Request side: buffered ───────────────────────────────────────────────────

// OnRequestBody masks or redacts PII in the fully-buffered request body.
// Returns RequestBodyAction — can carry HeaderMutation or ImmediateResponse
// because the request has not yet been forwarded to upstream.
func (p *PIIMaskingRegexPolicy) OnRequestBody(ctx *policy.RequestBodyContext) policy.RequestBodyAction {
	if ctx.Body == nil || len(ctx.Body.Content) == 0 {
		return policy.RequestBodyAction{}
	}

	extracted, err := extractStringValue(ctx.Body.Content, p.jsonPath)
	if err != nil {
		return p.rejectRequest(fmt.Sprintf("JSONPath extraction failed: %v", err))
	}
	extracted = strings.TrimSpace(textCleanRe.ReplaceAllString(extracted, ""))

	var modified string
	if p.redactPII {
		modified = p.redact(extracted)
	} else {
		modified, err = p.mask(extracted, ctx.Metadata)
		if err != nil {
			return p.rejectRequest(fmt.Sprintf("PII masking failed: %v", err))
		}
	}

	if modified == "" || modified == extracted {
		return policy.RequestBodyAction{}
	}

	updated := applyToPayload(ctx.Body.Content, extracted, modified, p.jsonPath)
	return policy.RequestBodyAction{BodyMutation: updated}
}

// ─── Response side: streaming ─────────────────────────────────────────────────

// OnResponseBody is the buffered fallback required by StreamingResponseBodyPolicy.
// It is invoked by the kernel whenever the response body is delivered in BUFFERED
// mode (Envoy assembled the complete body before forwarding to ext_proc).
//
// This method is called in TWO distinct scenarios — the content format differs:
//
// ── Scenario A: Non-streaming upstream response ────────────────────────────────
//
//   Triggered when: upstream sends Content-Length (no Transfer-Encoding: chunked,
//   no Content-Type: text/event-stream). The kernel detects isStreaming=false and
//   forces BUFFERED mode regardless of chain capabilities.
//
//   Content received: complete plain JSON — one full response object.
//     {"id":"chatcmpl-xxx","choices":[{"message":{"content":"[EMAIL_0001] replied"}}],...}
//
//   Restoration: replaces all [TYPE_xxxx] placeholders in the JSON body.
//
// ── Scenario B: Streaming upstream but forced-BUFFERED chain ──────────────────
//
//   Triggered when: upstream sends SSE or chunked transfer (isStreaming=true) BUT
//   at least one policy in the chain does NOT implement StreamingResponseBodyPolicy
//   (StreamResponseBody=false).  The kernel overrides ResponseBodyMode to BUFFERED
//   at ResponseHeaders, so Envoy assembles ALL SSE chunks into one body.
//
//   Content received: every SSE event concatenated into a single string.
//     data: {"choices":[{"delta":{"content":"Hello "}}]}\n\n
//     data: {"choices":[{"delta":{"content":"[EMAIL_0001]"}}]}\n\n
//     ...
//     data: [DONE]\n\n
//
//   Restoration: global string replace scans the entire concatenated string and
//   restores all placeholder occurrences regardless of SSE event boundaries.
//   This is actually MORE reliable than per-event restoration because placeholders
//   split across events are visible in the full string.
func (p *PIIMaskingRegexPolicy) OnResponseBody(ctx *policy.ResponseBodyContext) policy.ResponseBodyAction {
	if ctx.ResponseBody == nil || len(ctx.ResponseBody.Content) == 0 {
		return policy.ResponseBodyAction{}
	}
	return p.restoreInChunk(ctx.ResponseBody.Content, ctx.Metadata)
}

// OnResponseBodyChunk processes the response in streaming (FULL_DUPLEX_STREAMED) mode.
// It is called by the kernel once per "flush" as determined by NeedsMoreData.
//
// This method is called in THREE distinct scenarios — the content format differs:
//
// ── Scenario 1: True SSE stream (streaming:true in request, all policies streaming) ─
//
//   Triggered when: upstream sends Content-Type: text/event-stream (isSSE=true)
//   AND all chain policies implement StreamingResponseBodyPolicy (StreamResponseBody=true).
//   The kernel uses FULL_DUPLEX_STREAMED mode.
//
//   NeedsMoreData flushes on "\n\n" → this method receives one complete SSE event
//   (possibly more if multiple events arrived in one raw Envoy chunk).
//
//   Content received (one flush):
//     data: {"id":"chatcmpl-xxx","choices":[{"delta":{"content":"[EMAIL"}}]}\n\n
//
//   ⚠ Split-placeholder limitation: LLMs generate text token by token, so a
//   placeholder like [EMAIL_0001] may be split across consecutive SSE events:
//     flush 1: ...{"content":"[EMAIL"}...     ← incomplete, not restored
//     flush 2: ...{"content":"_0001]"}...     ← incomplete, not restored
//   The placeholder will remain visible in the stream for those chunks.
//   This is the trade-off of per-event processing vs. full-body buffering.
//
// ── Scenario 2: Non-SSE chunked transfer (streaming:false but chunked encoding) ──
//
//   Triggered when: upstream sends Content-Type: application/json with
//   Transfer-Encoding: chunked (isChunked=true, isSSE=false).
//   Example: OpenAI non-streaming response over HTTP/1.1 — the JSON body is
//   still delivered via chunked transfer even though stream:false was requested.
//
//   NeedsMoreData (NeedsMoreDataSSE) finds no "\n\n" in plain JSON, so it holds
//   every raw chunk until eos=true.  This method then receives the COMPLETE
//   JSON body in a single call (chunk.EndOfStream=true).
//
//   Content received (single call, eos=true):
//     {"id":"chatcmpl-xxx","object":"chat.completion",
//      "choices":[{"message":{"content":"[EMAIL_0001] replied"}}],...}
//
//   Restoration: all placeholders are found and replaced in the full JSON body.
//
// ── Scenario 3: Forced-BUFFERED synthetic chunk (mixed-chain corner case) ─────
//
//   Triggered when: a co-located policy forces Envoy into BUFFERED mode but this
//   policy is still routed through the streaming path by the kernel.  The kernel
//   wraps the full assembled body as a single chunk with EndOfStream=true.
//   NeedsMoreData is bypassed (eos=true → unconditional flush).
//
//   Content received: either plain JSON or concatenated SSE events (same as
//   OnResponseBody Scenario B), as a single call with chunk.EndOfStream=true.
//
//   Restoration: global string replace works for both formats.
//
// Returns ResponseChunkAction. Response status and headers are already committed
// to the downstream client — only the chunk payload can be mutated.
func (p *PIIMaskingRegexPolicy) OnResponseBodyChunk(ctx *policy.ResponseStreamContext, chunk *policy.StreamBody) policy.ResponseChunkAction {
	if len(chunk.Content) == 0 {
		return policy.ResponseChunkAction{}
	}
	action := p.restoreInChunk(chunk.Content, ctx.Metadata)
	return policy.ResponseChunkAction{BodyMutation: action.BodyMutation}
}

// restoreInChunk is the shared restoration logic called by both OnResponseBody
// and OnResponseBodyChunk.  It intentionally uses a format-agnostic approach:
// a global strings.ReplaceAll scan on the raw bytes.
//
// Why format-agnostic works for all content types:
//
//   Plain JSON:       {"content": "[EMAIL_0001] replied"} → placeholder restored inline
//   SSE event:        data: {"delta":{"content":"[EMAIL_0001]"}}\n\n → restored in SSE JSON
//   Aggregated SSE:   data: {...[EMAIL_0001]...}\n\ndata: {...}\n\n → all occurrences restored
//   Partial token:    data: {"delta":{"content":"[EMAIL"}}\n\n → no match, passthrough ✓
//
// The last case (partial token) produces a passthrough with no error.  The
// incomplete placeholder is benign — it does not expose real PII, because the
// original PII was replaced on the request side and the LLM only echoes the
// placeholder string.  The split token will appear as-is in the stream.
func (p *PIIMaskingRegexPolicy) restoreInChunk(content []byte, metadata map[string]interface{}) policy.ResponseBodyAction {
	if p.redactPII {
		return policy.ResponseBodyAction{}
	}

	raw, exists := metadata[metadataKeyPII]
	if !exists {
		return policy.ResponseBodyAction{}
	}
	maskedMap, ok := raw.(map[string]string)
	if !ok || len(maskedMap) == 0 {
		return policy.ResponseBodyAction{}
	}

	restored := restorePlaceholders(string(content), maskedMap)
	if restored == string(content) {
		return policy.ResponseBodyAction{}
	}
	return policy.ResponseBodyAction{BodyMutation: []byte(restored)}
}

// ─── PII helpers ──────────────────────────────────────────────────────────────

// mask replaces PII with deterministic [TYPE_xxxx] placeholders and stores
// the original→placeholder mapping in metadata for response-side restoration.
func (p *PIIMaskingRegexPolicy) mask(content string, metadata map[string]interface{}) (string, error) {
	if content == "" {
		return "", nil
	}

	alreadyMasked := regexp.MustCompile(`^\[[A-Z_]+_[0-9a-f]{4}\]$`)
	allMatches := make(map[string]string)
	maskedEntities := make(map[string]string)
	counter := 0

	for entityName, pattern := range p.piiEntities {
		for _, match := range pattern.FindAllString(content, -1) {
			if _, exists := allMatches[match]; exists {
				continue
			}
			if alreadyMasked.MatchString(match) {
				continue
			}
			placeholder := fmt.Sprintf("[%s_%04x]", entityName, counter)
			allMatches[match] = placeholder
			maskedEntities[match] = placeholder
			counter++
		}
	}

	if len(allMatches) == 0 {
		return "", nil
	}

	// Replace longest originals first to avoid partial substitutions.
	originals := make([]string, 0, len(allMatches))
	for orig := range allMatches {
		originals = append(originals, orig)
	}
	sort.Slice(originals, func(i, j int) bool {
		return len(originals[i]) > len(originals[j])
	})
	result := content
	for _, orig := range originals {
		result = strings.ReplaceAll(result, orig, allMatches[orig])
	}

	metadata[metadataKeyPII] = maskedEntities
	return result, nil
}

// redact permanently replaces PII with "*****".
func (p *PIIMaskingRegexPolicy) redact(content string) string {
	if content == "" {
		return ""
	}
	result := content
	found := false
	for _, pattern := range p.piiEntities {
		if pattern.MatchString(result) {
			found = true
			result = pattern.ReplaceAllString(result, "*****")
		}
	}
	if found {
		return result
	}
	return ""
}

// restorePlaceholders replaces all known placeholder tokens with original values.
func restorePlaceholders(content string, maskedMap map[string]string) string {
	for original, placeholder := range maskedMap {
		if strings.Contains(content, placeholder) {
			content = strings.ReplaceAll(content, placeholder, original)
		}
	}
	return content
}

// ─── Payload helpers (REQUEST side only) ─────────────────────────────────────
//
// jsonPath is ONLY used on the request side to locate the text field that should
// be scanned for PII (e.g. "$.messages[0].content" for OpenAI chat requests).
//
// The response side does NOT use jsonPath at all.  Here is why:
//
//   On the request side we know exactly where the user's text is — the OpenAI
//   API schema guarantees it lives at messages[0].content.
//
//   On the response side the text location DIFFERS by response type:
//     Non-streaming:  choices[0].message.content   (full chat.completion object)
//     Streaming SSE:  choices[0].delta.content      (chat.completion.chunk object)
//   Configuring two separate response jsonPaths would be fragile and coupling the
//   policy to the LLM wire format unnecessarily.
//
//   Instead, restoration is done via a global string replace on the raw response
//   bytes (see restoreInChunk).  The placeholder [EMAIL_0001] is a unique literal
//   string that appears in the response wherever the LLM echoed it back — whether
//   inside message.content, delta.content, or anywhere else.  The global replace
//   finds it regardless of JSON structure and works identically for:
//     • plain JSON (non-streaming)
//     • SSE event chunks (streaming, one flush per event)
//     • aggregated SSE (streaming but forced-buffered chain)

// pathSegment represents one navigation step in a dotted JSON path.
// Examples from "$.messages[0].content":
//
//	Step 1: key="messages" isArray=true  index=0   → navigate into messages[0]
//	Step 2: key="content"  isArray=false index=0   → read the string field
func extractStringValue(payload []byte, jsonPath string) (string, error) {
	if jsonPath == "" {
		return string(payload), nil
	}
	var doc map[string]interface{}
	if err := json.Unmarshal(payload, &doc); err != nil {
		return "", fmt.Errorf("invalid JSON: %w", err)
	}
	key := strings.TrimPrefix(jsonPath, "$.")
	v, ok := doc[key]
	if !ok {
		return "", fmt.Errorf("key %q not found", key)
	}
	s, ok := v.(string)
	if !ok {
		return "", fmt.Errorf("value at %q is not a string", key)
	}
	return s, nil
}

func applyToPayload(original []byte, _, modified, jsonPath string) []byte {
	if jsonPath == "" {
		return []byte(modified)
	}
	var doc map[string]interface{}
	if err := json.Unmarshal(original, &doc); err != nil {
		return []byte(modified)
	}
	key := strings.TrimPrefix(jsonPath, "$.")
	doc[key] = modified
	updated, err := json.Marshal(doc)
	if err != nil {
		return original
	}
	return updated
}

// ─── Parameter parsing ────────────────────────────────────────────────────────

func parsePIIEntities(params map[string]interface{}) (map[string]*regexp.Regexp, error) {
	raw, ok := params["piiEntities"]
	if !ok {
		return nil, fmt.Errorf("'piiEntities' is required")
	}

	var items []map[string]interface{}
	switch v := raw.(type) {
	case string:
		if err := json.Unmarshal([]byte(v), &items); err != nil {
			return nil, fmt.Errorf("cannot parse 'piiEntities' JSON string: %w", err)
		}
	case []interface{}:
		items = make([]map[string]interface{}, 0, len(v))
		for i, item := range v {
			m, ok := item.(map[string]interface{})
			if !ok {
				return nil, fmt.Errorf("piiEntities[%d] must be an object", i)
			}
			items = append(items, m)
		}
	default:
		return nil, fmt.Errorf("'piiEntities' must be an array")
	}

	if len(items) == 0 {
		return nil, fmt.Errorf("'piiEntities' cannot be empty")
	}

	namePattern := regexp.MustCompile(`^[A-Z_]+$`)
	entities := make(map[string]*regexp.Regexp, len(items))

	for i, item := range items {
		name, err := requireString(item, "piiEntity", fmt.Sprintf("piiEntities[%d]", i))
		if err != nil {
			return nil, err
		}
		if !namePattern.MatchString(name) {
			return nil, fmt.Errorf("piiEntities[%d].piiEntity must match ^[A-Z_]+$", i)
		}
		if _, dup := entities[name]; dup {
			return nil, fmt.Errorf("duplicate piiEntity: %q", name)
		}
		pattern, err := requireString(item, "piiRegex", fmt.Sprintf("piiEntities[%d]", i))
		if err != nil {
			return nil, err
		}
		compiled, err := regexp.Compile(pattern)
		if err != nil {
			return nil, fmt.Errorf("piiEntities[%d].piiRegex is invalid: %w", i, err)
		}
		entities[name] = compiled
	}

	return entities, nil
}

func requireString(m map[string]interface{}, key, prefix string) (string, error) {
	v, ok := m[key]
	if !ok {
		return "", fmt.Errorf("%s.%s is required", prefix, key)
	}
	s, ok := v.(string)
	if !ok || s == "" {
		return "", fmt.Errorf("%s.%s must be a non-empty string", prefix, key)
	}
	return s, nil
}

// ─── Error helpers ────────────────────────────────────────────────────────────

func (p *PIIMaskingRegexPolicy) rejectRequest(reason string) policy.RequestBodyAction {
	body, err := json.Marshal(map[string]interface{}{
		"code":    internalErrorCode,
		"message": "pii-masking-regex error: " + reason,
	})
	if err != nil {
		body = []byte(fmt.Sprintf(`{"code":%d,"message":"internal error"}`, internalErrorCode))
	}
	return policy.RequestBodyAction{
		ImmediateResponse: &policy.ImmediateResponse{
			Status:  internalErrorStatus,
			Headers: map[string]string{"Content-Type": "application/json"},
			Body:    body,
		},
	}
}
